### ISSUE TITLE
poland-en failing to insert to Dynamo

### ISSUE THREAD

**Issue by shenanigansd** [Ukraine-Relief-Efforts/scraper#144]
The `poland-en` data is failing to be updated in Dynamo. The full traceback is below:

```
Traceback (most recent call last):
  File "/var/task/utils/dynamo.py", line 110, in write_to_dynamo
    client.put_item(
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 691, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/runtime/botocore/client.py", line 739, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/runtime/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Item.reception.L[0].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[0].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[1].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[1].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[2].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[2].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[3].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[3].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[4].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[4].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[5].M.lat.S, value: 49.805569, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[5].M.lon.S, value: 22.930681, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[6].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[6].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[7].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[7].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[8].M.lat.S, value: 14.655657, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[8].M.lon.S, value: 120.980764, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[9].M.lat.S, value: 39.78373, type: <class 'float'>, valid types: <class 'str'>
Invalid type for parameter Item.reception.L[9].M.lon.S, value: -100.445882, type: <class 'float'>, valid types: <class 'str'>
```

**Comment by Jachdich** [comment]
Looks like a simple fix, will implement that just now
